POST http://localhost:5000/api/wilder
Content-Type: application/json

{
    "name": "REST Client Wilder 2"
}

###
GET http://localhost:5000/api/wilder

###
DELETE http://localhost:5000/api/wilder/3

###
PUT http://localhost:5000/api/wilder/2
Content-Type: application/json

{
    "name": "Alice"
}